name: 'Gluon Build'
description: 'Action to build a Gluon application.'
inputs:
  gluon-license:
    description: 'Optional Gluon license'
    required: false
  target:
    description: 'The target platform to build: desktop, ios, android'
    required: true  
runs:
  using: "composite"
  steps: 
    - name: setup android certs
      run: |
          printf "${{ inputs.GLUON_ANDROID_KEYSTORE_BASE64 }}" > $GITHUB_WORKSPACE/keystore.base64
          base64 -d $GITHUB_WORKSPACE/keystore.base64 > $GITHUB_WORKSPACE/my.keystore
          ls -l $GITHUB_WORKSPACE/my.keystore  
      shell: bash
    - run: printf "${{ inputs.gluon-license }}" > src/main/resources/gluonmobile.license
      shell: bash
    - run: mvn -DconsoleProcessLog=true -P${{ inputs.target }} client:build client:package
      shell: bash
      env:
        GRAALVM_HOME: ${{ env.JAVA_HOME }}
        GLUON_ANDROID_KEYSTOREPATH: ${{ env.GITHUB_WORKSPACE }}/my.keystore
        GLUON_ANDROID_KEYSTORE_PASSWORD: ${{ inputs.GLUON_ANDROID_KEYSTORE_PASSWORD }}
        GLUON_ANDROID_KEYALIAS: ${{ inputs.GLUON_ANDROID_KEYALIAS }}
        GLUON_ANDROID_KEYALIAS_PASSWORD: ${{ inputs.GLUON_ANDROID_KEYALIAS_PASSWORD }}
        Path: ${{ inputs.Path }}
        PSModulePath: ${{ inputs.PSModulePath }}
        LIBPATH: ${{ inputs.LIBPATH }}
        LIB: ${{ inputs.LIB }}
